version: 2
jobs: 
  test: 
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - publish
